use amrs;
SET FOREIGN_KEY_CHECKS = 0;
ALTER TABLE amrs.obs ADD UNIQUE KEY `obs_uuid_index`  (`uuid`);
select 'obs_uuid_index',now();
ALTER TABLE amrs.obs ADD KEY `answer_concept` (`value_coded`);
select 'answer_concept',now();
ALTER TABLE amrs.obs ADD KEY `encounter_observations` (`encounter_id`);
select 'encounter_observations',now();
ALTER TABLE amrs.obs ADD KEY `obs_concept` (`concept_id`);
select 'obs_concept',now();
ALTER TABLE amrs.obs ADD KEY `obs_enterer` (`creator`);
select 'obs_enterer',now();
ALTER TABLE amrs.obs ADD KEY `obs_location` (`location_id`);
select 'obs_location',now();
ALTER TABLE amrs.obs ADD KEY `obs_order` (`order_id`);
select 'obs_order',now();
ALTER TABLE amrs.obs ADD KEY  `patient_obs` (`person_id`);
select 'patient_obs',now();
ALTER TABLE amrs.obs ADD KEY `user_who_voided_obs` (`voided_by`);
select 'user_who_voided_obs',now();
ALTER TABLE amrs.obs ADD KEY `answer_concept_drug` (`value_drug`);
select 'answer_concept_drug',now();
ALTER TABLE amrs.obs ADD KEY `datetime_of_observation` (`obs_datetime`);
select 'datetime_of_observation',now();
ALTER TABLE amrs.obs ADD KEY `voided_status_of_observation` (`voided`);
select 'voided_status_of_observation',now();
ALTER TABLE amrs.obs ADD KEY `obs_grouping_id` (`obs_group_id`);
select 'obs_grouping_id',now();
ALTER TABLE amrs.obs ADD KEY `obs_name_of_coded_value` (`value_coded_name_id`);
select 'obs_name_of_coded_value',now();
ALTER TABLE amrs.obs ADD KEY `obs_datetime_idx` (`obs_datetime`);
select 'obs_datetime_idx',now();
ALTER TABLE amrs.obs ADD KEY `obs_voided_person_concept_obsdate_idx` (`voided`,`person_id`,`concept_id`,`obs_datetime`);
select 'obs_voided_person_concept_obsdate_idx',now();
ALTER TABLE amrs.obs ADD KEY `obs_complex_cvCpvoD_idx` (`concept_id`,`value_coded`,`person_id`,`voided`,`obs_datetime`);
select 'obs_complex_cvCpvoD_idx',now();
ALTER TABLE amrs.obs ADD  KEY `obs_complex_cpvvD_idx` (`concept_id`,`person_id`,`voided`,`value_datetime`);
select 'obs_complex_cpvvD_idx',now();
ALTER TABLE amrs.obs ADD  KEY `date_created` (`date_created`);
select 'date_created',now();
ALTER TABLE amrs.obs ADD KEY `date_voided` (`date_voided`);
select 'date_voided',now();
ALTER TABLE amrs.obs ADD KEY `previous_version` (`previous_version`);
select 'previous_version',now();
ALTER TABLE amrs.obs ADD KEY `person_date` (`voided`,`encounter_id`,`person_id`,`obs_datetime`);
select 'person_date',now();